# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-03-09 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateUar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255, unique=True, verbose_name='course')),
                ('AdicText', models.CharField(max_length=100, verbose_name='Texto Adicional')),
            ],
            options={
                'ordering': ('course_id',),
            },
        ),
    ]
