# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-10-20 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_uar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateuar',
            name='Chours',
            field=models.IntegerField(default=0, verbose_name='Horas Curso'),
        ),
        migrations.AddField(
            model_name='certificateuar',
            name='Format',
            field=models.CharField(default='uar', max_length=30, verbose_name='Formato'),
        ),
    ]
